#cloud-config
users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM5m9AhMRWiO+yybLYEHaJhFaODFZDTbOiYqitAxzWgs alexey@dell

packages:
  - nginx

runcmd:
  - echo "<h1>Hello from $(hostname)</h1>" > /var/www/html/index.html
  - systemctl enable nginx
  - systemctl restart nginx
