# cloud-init-filebeat.yml — установка Filebeat и отправка логов nginx в Elasticsearch

#cloud-config
package_update: true
packages:
  - apt-transport-https
  - wget
  - curl

runcmd:
  - curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
  - apt-get install -y gnupg
  - echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" > /etc/apt/sources.list.d/elastic-7.x.list
  - apt-get update && apt-get install -y filebeat

  # Настройка Filebeat для отправки логов Nginx
  - filebeat modules enable nginx
  - |
    cat > /etc/filebeat/filebeat.yml <<EOF
    filebeat.inputs:
    - type: filestream
      enabled: true
      paths:
        - /var/log/nginx/access.log
        - /var/log/nginx/error.log

    output.elasticsearch:
      hosts: ["http://<PRIVATE_IP_ELASTIC>:9200"]
      index: "nginx-logs-%{+yyyy.MM.dd}"

    setup.kibana:
      host: "http://<PUBLIC_IP_KIBANA>:5601"
    EOF

  - systemctl daemon-reexec
  - systemctl enable filebeat
  - systemctl start filebeat
