# cloud-init-grafana.yml — установка и базовая настройка Grafana

#cloud-config
packages:
  - apt-transport-https
  - software-properties-common
  - wget
  - gnupg2

runcmd:
  - wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -
  - add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"
  - apt-get update
  - apt-get install -y grafana
  - systemctl daemon-reexec
  - systemctl enable grafana-server
  - systemctl start grafana-server

  # Добавление Prometheus как источник данных
  - sleep 10
  - |
    curl -X POST http://localhost:3000/api/datasources \
      -H "Content-Type: application/json" \
      -H "Authorization: Basic $(echo -n admin:admin | base64)" \
      -d '{
        "name": "Prometheus",
        "type": "prometheus",
        "url": "http://<PROMETHEUS_INTERNAL_IP>:9090",
        "access": "proxy",
        "basicAuth": false
      }'
