# cloud-init-elasticsearch.yml — установка и запуск Elasticsearch

#cloud-config
package_update: true
packages:
  - apt-transport-https
  - openjdk-11-jdk
  - wget

runcmd:
  - wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
  - apt-get install -y gnupg
  - echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" > /etc/apt/sources.list.d/elastic-7.x.list
  - apt-get update && apt-get install -y elasticsearch
  - sed -i 's/#network.host: .*/network.host: 0.0.0.0/' /etc/elasticsearch/elasticsearch.yml
  - systemctl daemon-reexec
  - systemctl enable elasticsearch
  - systemctl start elasticsearch
