#cloud-config
users:
  - name: user
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 LeQiLNoJFza2ep3pcOoqi6wBn3bld4mZVQhQG4O4m2g alexey@dell
